// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Replace this comment with your code 
		int N = Integer.parseInt(args[0]);
		int above = 0;
		int under = 0;
		double ratio = 0; 
		for (int i = 0; i < N; i++) {
			double r = Math.random();
			if (r > 0.5) { 
				above ++; 
			}
			else {
				under ++;
			}
			
		}
		System.out.println("> 0.5: " + above + " times");
	    System.out.println("<= 0.5: " + under + " times");
		if (above != 0 && under != 0){
         ratio = ((double)above / under); 
		 System.out.println("Ratio: " + ratio);
		}
		

	}
}
